/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameLogsRouteImport } from './routes/game-logs'

const GameLogsRoute = GameLogsRouteImport.update({
  id: '/game-logs',
  path: '/game-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/game-logs': typeof GameLogsRoute
}
export interface FileRoutesByTo {
  '/game-logs': typeof GameLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/game-logs': typeof GameLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/game-logs'
  fileRoutesByTo: FileRoutesByTo
  to: '/game-logs'
  id: '__root__' | '/game-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameLogsRoute: typeof GameLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game-logs': {
      id: '/game-logs'
      path: '/game-logs'
      fullPath: '/game-logs'
      preLoaderRoute: typeof GameLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GameLogsRoute: GameLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
